### PR TITLE
PR-Hactoberfest2022_added_new_java_question

### PR DESCRIPTION
**Pull request by rakshith6404**
I have added a new java question which is most commonly asked in interview questions regarding the issue #60 
I am looking forward to merge this file - Hactobefest2022 :smile:

### CODE REVIEW

**Comment by creater-shikha** [comment]
i will definetly do this , plz add hacktoberfest2022  label so that the PR count in contest

**Comment by rakshith6404** [comment]
I dont have the right to make a label for the same as i am just a contributor
if you can merge it then it automatically will reflect in my hacktoberfest page 
Looking forward to merge this please merge it. :smile:

**Comment by rakshith6404** [comment]
image
You just have to accept it :smile:

**Comment by rakshith6404** [comment]
Cool you just have to merge this request if you feel like to do .
That would be counted smile:

**Pull request closed without merging**
